apiVersion: v1
kind: Namespace
metadata:
  name: network-ranger

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: network-ranger
  name: network-ranger-web
  labels:
    app: network-ranger-web

spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-ranger-web
  template:
    metadata:
      labels:
        app: network-ranger-web
    spec:
      containers:
        - name: network-ranger-web
          image: netdiscord/network-ranger-web:latest
          ports:
            - containerPort: 5000
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: TOKEN
            - name: GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: GUILD_ID
            - name: OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: OAUTH2_CLIENT_ID
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: OAUTH2_CLIENT_SECRET
            - name: MONGO_HOST
              value: "mongodb:27017"
            - name: MONGO_USER
              value: "root"
            - name: MONGO_NAME
              value: "network_ranger"
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            - name: NRWEB_ENVIRONMENT
              value: "dev"
            - name: OAUTH2_REDIRECT_URI
              value: "http://localhost:5000/login_callback"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: network-ranger
  labels:
    app: network-ranger-web
  name: network-ranger-web-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: network-ranger-web
  type: ClusterIP
