apiVersion: v1
kind: Namespace
metadata:
  name: network-ranger

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: network-ranger
  name: network-ranger-web
  labels:
    app: network-ranger-web

spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-ranger-web
  template:
    metadata:
      labels:
        app: network-ranger-web
    spec:
      containers:
        - name: network-ranger-web
          image: netdiscord/network-ranger-web:latest
          ports:
            - containerPort: 5000
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: TOKEN
            - name: GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: GUILD_ID
            - name: OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: OAUTH2_CLIENT_ID
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: OAUTH2_CLIENT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: DB_HOST
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: DB_PASS
            - name: DB_NAME
              value: "netranger"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: SECRET_KEY
            - name: NRWEB_ENVIRONMENT
              value: "prod"
            - name: OAUTH2_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: network-ranger
                  key: OAUTH2_REDIRECT_URI
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: network-ranger
  labels:
    app: network-ranger-web
  name: network-ranger-web-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: network-ranger-web
  type: ClusterIP
