name: Docker Image CI

on:
  push:
    branches: [ main next ]
  pull_request:
    branches: [ main next ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag network-ranger-web:$(date +%s)
